### ISSUE TITLE
やること

### ISSUE THREAD

**Issue by himanoa** [tonkatsu-ansin/kogasa-bot#2]
* heroku -> bluemix
* SW2.0 キャラメイクするコマンド
* GitHubのステータス

**Comment by potato4d** [comment]
Bluemixにするんか

**Comment by himanoa** [comment]
heroku色々しんどいわ

**Comment by potato4d** [comment]
なるほど（なるほど）

**Comment by potato4d** [comment]
普通にReview Apps専用にするのが一番幸せだと思う（アレで全部賄うものではない）

**Comment by himanoa** [comment]
Review Apps is 何

**Comment by potato4d** [comment]
そうかこっちkogasa-botかｗ

**Comment by himanoa** [comment]
:smile:

**Comment by himanoa** [comment]
bluemix結局意味不明だったしア
